# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Shalu Nigam 
email: snigam00@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal and Research page of Dr. Shalu Nigam
baseurl: "" # the subpath of your site, e.g. /blog
url: "shalunigam.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ShaluNigam
orcid_username: ORCID 
linkedin_username: shalunigam
scholar_username: Google Scholar
#github_username:  jekyll
about: Dr. Shalu Nigam is an advocate, activist and researcher working at the intersection of gender, law, governance, and human rights issues. She completed her PhD in Social Work. 
show_excerpts: True
# Build settings
theme: minima
plugins:
  - jekyll-feed
 
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
